language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t atumu1025/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true atumu1025/react-test npm test

after_success:
  - docker build -t atumu1025/multi-client ./client
  - docker build -t atumu1025/multi-nginx ./nginx
  - docker build -t atumu1025/multi-server ./server
  - docker build -t atumu1025/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push atumu1025/multi-client 
  - docker push atumu1025/multi-nginx 
  - docker push atumu1025/multi-server 
  - docker push atumu1025/multi-worker 